[[project]]
name     = "clj-simple-stats"
desc     = "Simple statistics for Clojure/Ring webapps"
link     = "https://github.com/tonsky/clj-simple-stats"
img      = "clj-simple-stats.svg"
roles    = ["Creator"]
period   = "Dec 2025"
stack    = "Clojure, DuckDB"

[[project]]
name     = "Instant DB"
desc     = "Optimization, new APIs, developer experience"
link     = "https://www.instantdb.com/"
img      = "instant.png"
roles    = ["Engineer"]
period   = "Dec 2024‚Äâ‚Äî‚ÄâSep 2025"
stack    = "Clojure, PostgreSQL, TypeScript"

[[project]]
name     = "Clojure+"
desc     = "A project that improves Clojure stdlib"
link     = "https://github.com/tonsky/clojure-plus"
img      = "clojure-plus.png"
roles    = ["Creator"]
period   = "Jan 2025‚Äâ‚Äî‚Äânow"
status   = "Launched"
stack    = "Clojure"
stars    = 201

[[project]]
name     = "Fast EDN"
desc     = "Drop-in replacement for clojure.edn that is 6 times faster"
link     = "https://github.com/tonsky/fast-edn"
img      = "fast-edn.svg"
roles    = ["Creator"]
period   = "Dec 2024"
status   = "Launched"
stack    = "Clojure"
stars    = 176

[[project]]
name     = "AlleKinos.de"
desc     = "No-nonsense movie showtimes site for every cinema in Germany"
link     = "https://allekinos.de/"
img      = "allekinos.webp"
roles    = ["Creator"]
period   = "May 2024"
status   = "Launched, 1500 visitors/day"
stack    = "Clojure, DataScript, application.garden"

[[project]]
name     = "clj-reload"
desc     = "Clojure library for dependency-aware code reloading during REPL sessions"
link     = "https://github.com/tonsky/clj-reload"
img      = "clj-reload.webp"
roles    = ["Creator"]
period   = "Jan 2024 ‚Äî Feb 2024"
status   = "Launched"
stack    = "Clojure"
stars    = 277

[[project]]
name     = "Humble UI"
desc     = "Clojure UI framework for cross-platform desktop apps"
link     = "https://github.com/HumbleUI/HumbleUI"
img      = "humble-ui.webp"
roles    = ["Creator"]
period   = "Oct 2021 ‚Äî now"
status   = "Ongoing"
stack    = "Clojure"
stars    = 1163

[[project]]
name     = "Clojure Sublimed"
desc     = "#1 Clojure development environment (syntax, indentener, REPL) for Sublime Text 4"
link     = "https://github.com/tonsky/Clojure-Sublimed"
img      = "clojure-sublimed.webp"
roles    = ["Creator"]
period   = "Dec 2021 ‚Äî now"
status   = "Launched"
stack    = "Python"
installs = 2468
[[project.quote]]
text     = "This is an exceptionally well thought out set of points on REPL use for a lang like Clojure."
source   = "<a href='https://news.ycombinator.com/item?id=29551320'>rajandatta</a> on Hacker News"
[[project.quote]]
text     = "Some features I wish existed on CIDER, since I‚Äôm more used to Emacs. Nice job!"
source   = "<a href='https://www.reddit.com/r/Clojure/comments/rflhxf/sublime_clojure/hoemcoe/'>Comment on Reddit</a>"

[[project]]
name     = "Roam Research"
desc     = "Optimized DataScript persistence to reduce graph loading times down to several times"
link     = "https://roamresearch.com/"
img      = "roam.webp"
roles    = ["Consultant"]
period   = "May 2021 ‚Äî July 2023"
stack    = "ClojureScript, DataScript"

[[project]]
name     = "JWM"
desc     = "Cross-platform window management and OS integration library for Java."
link     = "https://github.com/HumbleUI/JWM"
img      = "jwm.svg"
roles    = ["Creator"]
period   = "May 2021 ‚Äî now"
status   = "Ongoing"
stack    = "Java, C++, ObjectiveC"
stars    = 544

[[project]]
name     = "Skija"
desc     = "High-quality JVM bindings for <a href='https://skia.org/'>Skia graphics library</a>."
link     = "https://github.com/humbleui/skija"
img      = "skija.webp"
roles    = ["Principal Engineer"]
period   = "March 2020 ‚Äî now"
status   = "Ongoing"
customer = "<a href='https://www.jetbrains.com/company/'>JetBrains GmbH</a>"
stack    = "Java, C++, OpenGL, Metal, DirectX"
used-by  = ["Humble UI", "JetBrains Fleet", "Jetpack Compose Desktop"]
stars    = 461
[[project.quote]]
text     = "I'm continually impressed by the stuff that comes out of the Clojure community. They really seem to punch above their weight in terms of useful output, novel ideas, interesting projects/products."
source   = "<a href='https://news.ycombinator.com/item?id=25129608'>uDontKnowMe</a> on Hacker News"

[[project]]
link     = "https://github.com/jetbrains/noria-clj"
img      = "noria.webp"
name     = "Noria"
desc     = "Experimental high-performance, declarative desktop UI framework for the JVM."
roles    = ["Software Engineer", "UX consultant"]
period   = "May 2019 ‚Äî March 2020"
status   = "Closed alpha"
customer = "<a href='https://www.jetbrains.com/company/'>JetBrains GmbH</a>"
stack    = "Clojure, Kotlin, Rust, WebRender"

[[project]]
link     = "https://fibery.io/"
img      = "fibery.webp"
name     = "Fibery"
desc     = "First work management platform with truly flexible domain."
roles    = ["Developer"]
period   = "April‚Äâ‚Äî‚ÄâJune 2018"
status   = "Closed beta"
customer = "<a href='https://www.targetprocess.com/about/'>Targetprocess Ltd</a>"
stack    = "Clojure, core.async, PostgreSQL"
[[project.quote]]
text     = "[Nikita has] good development speed. Quickly got the hang of things. Great quality of code and solutions. Reliable, can delegate any task and be sure it‚Äôll be done."
source   = "<a href='https://twitter.com/mdubakov'>Michael Dubakov</a>, founder"

[[project]]
link     = "https://grumpy.website"
name     = "Grumpy Website"
img      = "grumpy.webp"
desc     = "Collective blog with an in-depth look into UI/UX and design pitfalls of modern day interfaces. Tech: from-the-scratch blog engine developed <a href='https://www.youtube.com/playlist?list=PLdSfLyn35ej8por7aH-5wYvOyDTu-bPoH'>live¬†on¬†YouTube</a> in mere 36 hours."
roles    = ["Developer", "Co-Author"]
period   = "September 2017‚Äâ‚Äî‚Äânow"
status   = "In production, actively used"
stack    = "Clojure/Script, Rum/React"
visitors = 32000
[[project.quote]]
text     = "If you are into product and design, you should check out grumpy.website. It¬†has a lot of constructive feedback for y'all designers. (Think¬†LittleBigDetails.com with a Slavic spin üòì)"
source   = "<a href='https://twitter.com/NotionHQ/status/979088664339689472'>Notion</a>, the all-in-one workspace"

[[project]]
img      = "builder2.webp"
name     = "Collaborative document editor"
desc     = "In-browser, real-time, collaborative WYSIWYG editor for complex domain-specific documents."
roles    = ["UI/UX designer", "Architect", "Lead developer"]
team     = "3 Clojure Engineers"
customer = "<a href='https://www.cognician.com/'>Cognician, Inc</a>"
period   = "September 2017‚Äâ‚Äî‚ÄâApril 2018"
status   = "Ongoing. Completed: UI, architecture, functional prototype"
stack    = "Clojure/Script, Datomic, DataScript, Rum/React, custom Datomic-DataScript sync layer"
[[project.quote]]
text     = "Nikita's productivity is phenomenal (he built a substantial portion of @cognician with us for a while). This'll be dollars well-spent!"
source   = "<a href='https://twitter.com/RobStuttaford/status/1041789798871179266'>Robert Stuttaford</a>, CTO, Cognician"

[[project]]
link     = "https://www.cognician.com/methodology"
img      = "chat.jpg"
name     = "Coaching platform"
desc     = "Next generation of an in-browser (including mobile) self-serve coaching platform, developed from ground up in place of a legacy system."
roles    = ["Architect", "Lead developer", "Product manager"]
customer = "<a href='https://www.cognician.com/'>Cognician, Inc</a>"
period   = "March 2015‚Äâ‚Äî‚ÄâAugust 2015"
status   = "In production, actively used. Fully replaced legacy system, ongoing feature development and maintenance"
stack    = "Clojure/Script, Datomic, DataScript, Rum/React, custom Event Sourcing implementation, custom client-server sync layer"
[[project.quote]]
text     = "[Nikita] single-handedly built crucial parts of our system, with great efficiency and level-headedness [...] I can't recommend Nikita highly enough. If you can find a way to work with him, do!"
source   = "<a href='https://twitter.com/RobStuttaford/status/984832783469219842'>Robert Stuttaford</a>, CTO, Cognician"

[[project]]
link     = "https://github.com/tonsky/AnyBar"
img      = "anybar.webp"
name     = "AnyBar"
stars    = 5980
desc     = "General-purpose macOS menubar status indicator."
roles    = ["Creator"]
period   = "March 2015‚Äâ‚Äî‚ÄâAugust 2016"
status   = "Stable"

[[project]]
link     = "https://github.com/tonsky/rum"
name     = "Rum"
img      = "rum.svg"
stars    = 1777
desc     = "Simple, decomplected, isomorphic HTML UI library for ClojureScript (based on React) and Clojure (custom Server-Side Rendering implementation)."
roles    = ["Creator"]
used-by  = [
  "<a href='https://www.cognician.com'>Cognician</a>",
  "<a href='https://attendify.com'>Attendify</a>",
  "<a href='https://partsbox.io'>PartsBox.io</a>",
  "<a href='https://modnaKasta.ua'>modnaKasta</a>",
  "<a href='http://childrensheartsurgery.info'>ChildrensHeartSurgery.info</a>",
  "<a href='http://mightyhype.com/'>Mighty Hype</a>",
  "<a href='https://xn--80abhddbmm5bieahtk5n.xn--p1ai/'>–ë–µ–∑–æ–ø–∞—Å–Ω—ã–µ–î–æ—Ä–æ–≥–∏.—Ä—Ñ</a>",
  "<a href='http://houstonindoor.com/2016'>TourneyBot</a>",
  "<a href='https://www.purposefly.com/'>PurposeFly</a>",
  "<a href='https://www.simply.co.za'>Simply</a>",
  "<a href='https://www.oscaro.com'>Oscaro.com</a>"
]
period = "December 2014‚Äâ‚Äî‚Äânow"
status = "Stable. Ongoing feature development and maintenance"

[[project]]
link  = "https://github.com/tonsky/FiraCode"
img   = "firacode.webp"
name  = "Fira Code"
stars = 80300
desc  = "The most popular programming font with ligatures."
roles = ["Creator"]
used-by = [
  "<a href='https://www.jetbrains.com/'>JetBrains</a>",
  "<a href='https://codepen.io/'>CodePen</a>",
  "<a href='http://www.blink.sh/'>Blink¬†Shell</a>",
  "<a href='http://app.klipse.tech/'>Klipse</a>",
  "<a href='http://ilyabirman.net/'>IlyaBirman.net</a>",
  "<a href='https://evilmartians.com/'>EvilMartians.com</a>",
  "<a href='https://webmakerapp.com/'>Web¬†Maker</a>"
]
period = "November 2014‚Äâ‚Äî‚Äânow"
status = "Stable. Widely used, ongoing improvements"

[[project]]
link  = "https://github.com/tonsky/datascript"
img   = "datascript.svg"
name  = "DataScript"
stars = 5660
desc  = "Highly-flexible persistent in-memory storage and Datalog query engine for Clojure/Script and JS."
roles = ["Creator"]
used-by = [
  "<a href='https://roamresearch.com/'>Roam Research</a>",
  "<a href='http://logseq.com/'>LogSeq</a>",
  "<a href='https://github.com/athensresearch/athens'>Athens Research</a>",
  "<a href='https://www.hulunote.com/'>Hulunote</a>",
  "<a href='https://grumpy.website/'>Grumpy Website</a>",
  "<a href='http://precursorapp.com/'>Precursor</a>",
  "<a href='http://lightmesh.com/'>LightMesh</a>",
  "<a href='https://www.cognician.com/'>Cognician</a>",
  "<a href='http://www.bitfountain.io/'>bitfountain</a>",
  "<a href='https://partsbox.io/'>PartsBox</a>",
  "<a href='https://www.iamfy.co/'>I am Fy</a>",
  "<a href='http://www.zetawar.com'>Zetawar</a>",
  "<a href='https://www.lemmings.io'>Lemmings</a>"
]
period = "April 2014‚Äâ‚Äî‚Äânow"
status = "Stable. Ongoing feature development and maintenance"
[[project.quote]]
text   = "DataScript is a brilliant thing...undoubtedly the most widely deployed Datalog engine on the planet üî•"
source = "<a href='https://twitter.com/refset/status/1282311437453611008'>Jeremy Taylor</a> on Twitter"

[[project]]
link   = "https://clojurecourse.by"
img    = "clojurecourse.webp"
name   = "ClojureCourse.by"
desc   = "Online videos teaching Clojure language + homework + 200+ students in remote groups."
roles  = ["Developer", "teacher"]
team   = "8 people"
period = "April‚Äâ‚Äî‚ÄâMay 2014"
status = "Completed"

[[project]]
name     = "MZ Bench"
img      = "mz.svg"
desc     = "Distributed benchmarking/load-testing tool with cross-machine coordination and DSL scripting."
roles    = ["Lead developer", "Project manager", "Team leader"]
team     = "4 Erlang Engineers"
customer = "<a href='http://www.mz.com/'>MachineZone, Inc</a>"
period   = "February 2014‚Äâ‚Äî‚ÄâNovember 2014"
status   = "Prototype"
stack    = "Erlang"

[[project]]
link     = "https://web.archive.org/web/20130807223115/http://aboutecho.com/EchoPlatform/DataServerDemonstration"
img      = "dataserver.webp"
name     = "Echo DataServer"
desc     = "High-load real-time monitor/data crawler &amp; processing pipeline for Twitter, Facebook, Youtube and others."
roles    = ["Lead developer", "Team leader", "Product manager"]
team     = "8 Clojure Engineers"
customer = "<a href='http://www.aboutecho.com'>Echo</a>"
period   = "October 2011‚Äâ‚Äî‚ÄâFebruary 2014"
status   = "Active production use at the moment"
stack    = "Clojure, RabbitMQ, Redis"
[[project.quote]]
text     = "[Nikita] is well-versed in technology and can build scalable, reliable and high-performance systems from scratch. He can work directly with a product team to flesh out requirements and define deliverables."
source   = "<a href='https://www.linkedin.com/in/wadcom'>Vlad Skvortsov</a>, VP of Engineering, Echo"
[[project.quote]]
text     = "[Nikita] has personally hired and managed people and his team has created one of the most important products for the company in record time and with appreciable quality."
source   = "<a href='https://www.linkedin.com/in/lionet'>Lev Walkin</a>, Founder and CTO, Echo"
[[project.quote]]
text     = "Nikita has the ability to take team and project initiatives aligned with the business direction of the company. Nikita has strong communication skills, both to present his ideas and research and to listen and understand the organization around him and his team."
source   = "<a href='https://www.linkedin.com/in/cailloux'>Philippe Cailloux</a>, COO & VP of Product, Echo"

[[project]]
link     = "https://bitbucket.org/xored/spectre/src"
img      = "spectre.jpg"
name     = "Spectre Web framework"
desc     = "Web framework built from the grounds up, inspired by Django, with web sockets, for Fantom language."
roles    = ["Designer", "Lead Developer"]
customer = "<a href='http://www.xored.com/'>Xored Software, Inc</a>"
period   = "October 2010‚Äâ‚Äî‚ÄâOctober 2011"
status   = "Feature complete"

[[project]]
name     = "Various Java projects"
img      = "java.svg"
desc     = "Automation, billing, prototyping for big Russian industrial facilities."
roles    = ["Senior Java Developer", "Java Developer", "Team Leader"]
customer = "Sibirenergo-Billing, MSS-Systems, KB Inform"
period   = "August 2005‚Äâ‚Äî‚ÄâOctober 2010"

[[project]]
img    = "diploma.jpg"
name   = "Education"
desc   = "Master‚Äôs degree in Information Technology at <a href='http://fit.nsu.ru/'>Novosibirsk State University</a>."
roles  = ["Student"]
period = "2001‚Äâ‚Äî‚Äâ2007"
status = "Complete"
